"use client";

import { motion } from "framer-motion";

const features = [
  {
    title: "Full Autonomy",
    desc: "Configure once. The pipeline runs daily on GitHub Actions with zero manual intervention.",
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-accent-teal">
        <circle cx="12" cy="12" r="10" />
        <path d="M12 6v6l4 2" />
      </svg>
    ),
    size: "md",
  },
  {
    title: "Zero-Cost Architecture",
    desc: "Free tiers of Gemini, Groq, Edge-TTS, Pexels, Supabase, and GitHub Actions. No monthly bills.",
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-success">
        <path d="M12 1v22M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6" />
      </svg>
    ),
    size: "lg",
  },
  {
    title: "Configurable Schedule",
    desc: "Set your publishing cadence. Daily, weekly, or custom cron. AutoTube respects your rhythm.",
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-accent-cyan">
        <rect x="3" y="4" width="18" height="18" rx="2" />
        <path d="M16 2v4M8 2v4M3 10h18" />
      </svg>
    ),
    size: "sm",
  },
  {
    title: "AI Content Stack",
    desc: "Scripts, voice, thumbnails, and metadata all generated by AI. Professional output at machine speed.",
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-accent-indigo">
        <path d="M12 2a10 10 0 0110 10c0 2.5-1 4.8-2.6 6.4" />
        <path d="M12 2a10 10 0 00-10 10c0 2.5 1 4.8 2.6 6.4" />
        <path d="M2 12h20" />
        <path d="M12 2v20" />
        <path d="M4.5 4.5l15 15M19.5 4.5l-15 15" />
      </svg>
    ),
    size: "md",
  },
  {
    title: "Safety Rails",
    desc: "Keyword blacklists, AI disclosure enforcement, QA validation gates. Built for responsible automation.",
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-accent-violet">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
      </svg>
    ),
    size: "lg",
  },
  {
    title: "Operational Resilience",
    desc: "Exponential backoff retry, Telegram alerts, structured logging, run history. Enterprise-grade reliability.",
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-accent-teal">
        <path d="M12 2L2 7l10 5 10-5-10-5z" />
        <path d="M2 17l10 5 10-5" />
        <path d="M2 12l10 5 10-5" />
      </svg>
    ),
    size: "md",
  },
];

const sizeClasses: Record<string, string> = {
  sm: "col-span-1 row-span-1",
  md: "col-span-1 row-span-1",
  lg: "col-span-1 md:col-span-2 row-span-1",
};

export default function WhyItWins() {
  return (
    <section id="why" className="relative py-32">
      <div className="max-w-7xl mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <span className="text-xs tracking-widest text-white/30 uppercase mb-4 block">
            Why AutoTube
          </span>
          <h2 className="font-display text-4xl md:text-5xl font-bold mb-4">
            Built to <span className="text-gradient">Win</span>
          </h2>
          <p className="max-w-xl mx-auto text-white/40 text-sm md:text-base">
            Not just another AI wrapper. An operating system for YouTube publishing.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 max-w-5xl mx-auto">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
              className={`${sizeClasses[feature.size]} glass rounded-2xl p-8 hover:bg-white/[0.03] transition-all duration-500 hover:scale-[1.02]`}
            >
              <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center mb-4">
                {feature.icon}
              </div>
              <h3 className="font-display text-lg font-semibold text-white/90 mb-2">
                {feature.title}
              </h3>
              <p className="text-sm text-white/40 leading-relaxed">
                {feature.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
